### PR TITLE
dataserving: major modification of the dockerfile to run server and c…

### PR DESCRIPTION
**Pull request by ustiugov**
dataserving: major modification of the dockerfile to run server and clients with docker-entrypoint.sh scripts

### CODE REVIEW

**Comment by neo-apz** [comment]
Please remove this file:
`benchmarks/data-serving/client/.Dockerfile.swp`

**Comment by ustiugov** [comment]
Thx. here you are.

**Comment by neo-apz** [comment]
Now we have two commits, which could have been squashed to one. You should have amended your change to the previous commit and then used `push --force` to replace the commit here.
Please have this in mind next time such a thing happens.

**Comment by ustiugov** [comment]
make sense, thx!

**Pull request merged**
