### PR TITLE
Issue #21 is solved

### PR DESCRIPTION
**Pull request by nooshin-mirzadeh**
I updated the serf package.

### CODE REVIEW

**Comment by neo-apz** [comment]
Have you tested it?
Make sure this new version of `serf` is compatible with other packages and it's not going to create a problem.
Btw, it would have been better to have a single commit containing all these changes instead of 3 separated commits. Have this in your mind for future commits. :wink:

**Comment by nooshin-mirzadeh** [comment]
Yes! Of course, I've tested it. I built all the images again and try to run the workload. 

I will merge commits in future. ;)

**Comment by aledaglis** [comment]
Do an interactive rebase on your branch in order to squash redundant commits and/or rename the commit message(s) that will be pushed to the master. Then, force push the branch (with -f). The pull request will be automatically updated.

**Comment by neo-apz** [comment]
It's merged with `master`.

**Pull request closed without merging**
