### PR TITLE
Add scripts for data-analytics

### PR DESCRIPTION
**Pull request by ivonindza**
probably useful for testing on nodes

### CODE REVIEW

**Comment by ivonindza** [comment]
Well, it's not an automated test. It's just a set of scripts to build the image across nodes, start the master and slaves, and stop them. It could be used to create a test, but it's mainly useful to start things on multiple nodes with a single command.

**Comment by neo-apz** [comment]
You are right. But we had a discussion with @javpicorel and we decided to have all these kinda things under the `tests` folder. We'll move the rests of the scripts into another subfolder named travis.

**Comment by ivonindza** [comment]
I moved them to the tests directory, but I still think that's a bad idea. We should have a separate directory for little helper scripts.

**Comment by neo-apz** [comment]
OK. I guess now it's better.
Now, we have a single `scripts` folder. Your scripts are there along with the scripts we had for travis ci.

**Pull request merged**
