### PR TITLE
Add Hadoop 2.7.3

### PR DESCRIPTION
**Pull request by ivonindza**

### CODE REVIEW

**Comment by neo-apz** [comment]
I've created a new repo on DockerHub for hadoop (https://hub.docker.com/r/cloudsuite/hadoop/).
Could you please update the `.travis.yml` file as well?
BTW, we keep the documentation files (MD files) under the `docs` folder.

**Comment by ivonindza** [comment]
OK, updated

**Comment by neo-apz** [comment]
OK good, the images are successfully built.
The spell checker is complaining about some words in your docs:
https://travis-ci.org/ParsaLab/cloudsuite/jobs/172681495

Can you please check and if the words are fine, please add the to the dictionary (`tests/.aspell.en.pws`).

**Comment by ivonindza** [comment]
I think the word "hostnames" is fine :)

**Comment by neo-apz** [comment]
Now everything looks good, except that this branch is 3 commits behind the master and that causes some conflicts on the `tests/.aspell.en.pws` file. Could you please update this branch?

**Comment by ivonindza** [comment]
updated

**Pull request merged**
